packages:
  - "apps/*"
  - "packages/*"
  - "packages/command/*"
  - "packages/subagent/*"
  - "packages/skill/*"
  - "packages/session/*"

allowBuilds:
  better-sqlite3: true
  esbuild: true
overrides:
  react: 18.3.1
  "@types/react": 18.3.31
