import { describe, expect, it } from 'vitest';
import { hasTransactionDirective } from '@harness/shared';

describe('human-only transaction authority text policy', () => {
  it.each([
    'Buy.',
    'Evidence is mixed. Buy.',
    'You should buy BBCA.',
    'I recommend selling BBCA.',
    'BBCA is a buy.',
    'BBCA is a sell.',
    'Kira: BBCA is a Strong Buy.',
    'I recommend that you buy BBCA.',
    'I recommend buying BBCA.',
    'We should buy BBCA.',
    'You should not buy BBCA.',
    'Do not sell BBCA.',
    'I would buy BBCA here.',
    'Consider buying BBCA.',
    'My view is to buy BBCA.',
    'My recommendation is hold.',
    'BBCA is a strong buy.',
    'Increase your position.',
    'Reduce the position.',
    'Enter the position now.',
    'Exit the position.',
    'Allocate 20% of your portfolio to BBCA.',
    'Allocate 20% to BBCA.',
    'Place a limit order at 8,500.',
    'Place a limit order.',
    'Buy at 8,500.',
    'Use a stop loss at 8,000.',
    'Set a stop loss.',
    'Take profit at 10,000.',
    'Set your position size to 10%.',
    'Sebaiknya beli BBCA.',
    'Mending beli BBCA.',
    'Saya sarankan jual BBCA.',
    'Tahan saham ini.',
    'Tambah posisi.',
    'Kurangi posisi.',
    'Masuk sekarang.',
    'Keluar dari posisi.',
    'Keluar sekarang.',
    'Menurut saya, beli BBCA.',
    'Lebih baik beli BBCA.',
    'Jangan beli BBCA.',
    'Tidak usah jual BBCA.',
    'BBCA layak dibeli.',
    'Rekomendasi: beli BBCA.',
  ])('rejects a clear transaction directive: %s', (text) => {
    expect(hasTransactionDirective(text)).toBe(true);
  });

  it.each([
    'Foreign investors recorded net buy flow.',
    'Foreign investors recorded net sell flow.',
    'Sell-side estimates remain contextual.',
    'Buy-side expectations are background.',
    'The company announced a share buyback.',
    'Institutional holdings increased.',
    'Trading activity increased.',
    'Daily transaction data show higher volume.',
    'The analytical stance is bullish.',
    'The analytical stance is bearish.',
    'The analytical stance is neutral.',
    'Buy signals can be noisy.',
    'Sell orders increased yesterday.',
    'Hold periods affect returns.',
    'Exit multiples affect valuation.',
    'The broker rates BBCA "Strong Buy".',
    'The cited broker report says "Strong Buy".',
    '"Strong Buy" is an external analyst rating.',
    'If you buy 100 shares at 8,500, the gross cost is 850,000.',
    'The cited broker report labels the stock "Buy".',
  ])('allows financial analysis and factual vocabulary: %s', (text) => {
    expect(hasTransactionDirective(text)).toBe(false);
  });

  it.each([
    'Buy BBCA at 8,500.',
    'Sell BBCA at 9,000.',
    'Buy 100 shares of BBCA.',
    'Sell half your position.',
    'Hold onto BBCA.',
    "I'd buy BBCA.",
    "I'd sell BBCA.",
    'You may want to buy BBCA.',
    'Based on this evidence, buy BBCA.',
    'Given the valuation, sell BBCA.',
    'Buy BBCA if it drops below 8,000.',
    'If price falls, buy BBCA.',
    'Put 20% of your portfolio in BBCA.',
    'Take a 10% position in BBCA.',
    'Untuk sekarang, beli BBCA.',
    'Kalau saya, beli BBCA.',
    'Saya akan beli BBCA.',
    'Beli BBCA di 8.500.',
    'Jual dulu BBCA.',
    'Tahan dulu BBCA.',
    'Boleh beli BBCA.',
    'BBCA bagus untuk dibeli.',
    'BBCA menarik untuk dibeli.',
    'Ambil posisi di BBCA.',
    'Lepas posisi BBCA.',
    'Masuk di 8.500.',
    'Keluar di 9.000.',
    'Pasang stop loss di 8.000.',
    'Pasang order beli BBCA di 8.500.',
    'Pasang order beli di 8.500.',
    'Keep holding BBCA.',
    'Buy BBCA below 8,000.',
    'Buy BBCA if valuation falls.',
    'Hold BBCA for now.',
    'Place a limit order at 8,500.',
    'Execute the order now.',
    'Set a stop loss at 8,000.',
    'Take profit at 10,000.',
    'Pasang order beli di 8.500.',
    'Take profit di 10.000.',
    'Reduce your position.',
  ])('Round 3 Advisor RED blocks: %s', (text) => {
    expect(hasTransactionDirective(text)).toBe(true);
  });

  it.each([
    'Kira recommends buying BBCA.',
    'We recommend buying BBCA.',
    'Our recommendation is to buy BBCA.',
    'Recommendation: buy BBCA.',
    'You should enter BBCA.',
    'You should exit BBCA.',
    'I recommend entering BBCA.',
    'I recommend exiting BBCA.',
    'Do not enter BBCA.',
    'Do not exit BBCA.',
    "Don't enter BBCA.",
    "Don't exit BBCA.",
    'You should increase your position.',
    'You should reduce your position.',
    'I recommend increasing your position.',
    'I recommend reducing your position.',
    'We should increase our position.',
    'We should reduce our position.',
    'Kira merekomendasikan beli BBCA.',
    'Kami sarankan beli BBCA.',
    'Rekomendasi Kira adalah beli BBCA.',
    'Anda sebaiknya beli BBCA.',
    'Kamu sebaiknya beli BBCA.',
    'Anda harus jual BBCA.',
    'Kamu harus tahan BBCA.',
    'Anda sebaiknya keluar dari posisi.',
    'Kamu sebaiknya kurangi posisi.',
  ])('Round 4 semantic parity blocks: %s', (text) => {
    expect(hasTransactionDirective(text)).toBe(true);
  });

  it.each([
    'I recommend allocating 20% to BBCA.',
    'We recommend allocating 20% to BBCA.',
    'Kira recommends allocating 20% to BBCA.',
    'My recommendation is to allocate 20% to BBCA.',
    'Our recommendation is to allocate 20% to BBCA.',
    "Kira's recommendation is to allocate 20% to BBCA.",
    'I recommend setting your position size to 10%.',
    'We recommend setting the position size to 10%.',
    'Kira recommends setting your position size to 10%.',
    'My recommendation is to use a 10% position size.',
    'Our recommendation is to use a 10% position size.',
    'You should place a limit order at 8,500.',
    'You should execute the order now.',
    'I recommend placing a limit order at 8,500.',
    'I recommend executing the order now.',
    'We recommend placing a limit order.',
    'Kira recommends executing the order now.',
    'My recommendation is to place a limit order.',
    'Our recommendation is to execute the order.',
    'You should set a stop loss at 8,000.',
    'You should use a stop loss at 8,000.',
    'You should take profit at 10,000.',
    'I recommend setting a stop loss at 8,000.',
    'I recommend using a stop loss at 8,000.',
    'I recommend taking profit at 10,000.',
    'Kira recommends setting a stop loss at 8,000.',
    'Kira recommends taking profit at 10,000.',
  ])('Round 5 contract parity blocks: %s', (text) => {
    expect(hasTransactionDirective(text)).toBe(true);
  });

  it.each([
    'Companies allocate capital efficiently.',
    'Management can allocate capital through dividends.',
    'The company should allocate capital to expansion.',
    'Banks allocate capital under regulatory constraints.',
    'Brokers execute orders for clients.',
    'Market makers place orders throughout the session.',
    'Investors reduce exposure during periods of high volatility.',
    'Investors may reduce exposure during volatility.',
    'This is a buy-side indicator.',
    'BBCA is a buy-side favorite.',
    'This is a sell-side estimate.',
    'The stock is a hold-period example.',
    'Investors consider buying after earnings surprises.',
    'The broker says BBCA is a Strong Buy.',
    'According to Broker X, BBCA is a Strong Buy.',
    'Broker X labels BBCA a Buy.',
    'The analyst rates BBCA Sell.',
    'The cited research report calls BBCA a Hold.',
    'The source reports that traders placed limit orders near 8,500.',
    'The user says their stop loss is 8,000.',
    'Brokers execute client orders.',
    'Perusahaan sebaiknya membeli kembali sahamnya.',
    'Perusahaan disarankan menjual aset non-inti.',
    'Manajemen harus menahan ekspansi.',
    'Management allocates capital efficiently.',
    'The company should allocate capital to expansion.',
    'Banks allocate capital under regulatory constraints.',
    'The study compares different position sizes.',
    'The portfolio example uses a 10% position size.',
    'Market makers place orders throughout the session.',
    'The source reports that traders placed limit orders near 8,500.',
    'Broker X recommends placing a limit order at 8,500.',
    'The analyst recommends executing the order after confirmation.',
    'The user says their stop loss is 8,000.',
    'The source reports a take-profit level of 10,000.',
    'The broker report recommends a stop loss at 8,000.',
    'Perusahaan mengalokasikan modal ke capex.',
    'This is a buyback program.',
    'Buy-side expectations improved.',
    'Sell-side estimates weakened.',
    'Buy signals can be noisy.',
    'Sell orders increased yesterday.',
    'Hold periods affect returns.',
    'Exit multiples affect valuation.',
    'Broker X recommends buying BBCA.',
    'The analyst recommends buying BBCA.',
    'The cited report recommends Hold.',
    'Investors reduce exposure during periods of high volatility.',
    'Funds increased their positions last quarter.',
    'The shareholder reduced its position.',
    'Perusahaan sebaiknya membeli kembali sahamnya.',
    'Perusahaan disarankan menjual aset non-inti.',
    'Manajemen harus menahan ekspansi.',
    'The broker rates BBCA "Strong Buy".',
    'Foreign investors recorded net buy flow.',
    'Foreign investors recorded net sell flow.',
    'The company announced a buyback.',
    'Institutional holdings increased.',
    'The analytical stance is bullish.',
    'The analytical stance is bearish.',
    'The analytical stance is neutral.',
    'If you buy 100 shares at 8,500, gross cost is 850,000.',
  ])('Round 3 Advisor RED allows: %s', (text) => {
    expect(hasTransactionDirective(text)).toBe(false);
  });

  it('blocks a directive after an externally attributed rating', () => {
    expect(hasTransactionDirective('According to Broker X, BBCA is a Strong Buy. Buy BBCA now.')).toBe(true);
  });
});
